export const USER_ACTION_TYPES = {
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SET_USER: "SET_USER",
  SET_USER_SUCCESS: "SET_USER_SUCCESS",
  SET_USER_FAILED: "SET_USER_FAILED",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_IS_AUTHENTICATED: "SET_IS_AUTHENTICATED",
  LOGIN_WITH_GOOGLE: "LOGIN_WITH_GOOGLE",
  LOGIN_WITH_GOOGLE_SUCCESS: "LOGIN_WITH_GOOGLE_SUCCESS",
};
